### ISSUE TITLE
Script para lanzar el container, y correr attach si ya esta corriendo

### ISSUE THREAD

**Issue by serraramiro1** [Ekumen-OS/Noah-bot-simulation#8]
Es engorroso para trabajar, tener que correr
```
docker attach -it ....
```
Cada vez que queremos abrir una nueva terminal, un proceso que ocurre a menudo trabajando con ROS.

Esto podria solucionarse con un pequeno script, que cree el container si no esta corriendo, o corra el commando anteriormente mencionado si el container ya esta corriendo.

**Comment by JCarosella** [comment]
PR mergeado, cierro issue!
